const fs = require('fs');
const path = require('path');

const mockDataPath = path.join(__dirname, '../../src/constants/mockData.js');
let mockDataContent = fs.readFileSync(mockDataPath, 'utf8');

const newCompanies = [
  {
    id: 'microchip',
    name: 'Microchip',
    logo: 'https://logo.clearbit.com/microchip.com',
    ctc: '10 LPA + 5 Lakh RSUs',
    tier: 'Core / Premium',
    description: 'Microchip Technology campus recruitment for embedded software and hardware design. CGPA Cutoff: 7.5. Eligible Depts: All SEEE & Core engineering branches.',
    tags: ['Core', 'Semiconductors', 'CGPA: 7.5', 'Embedded'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'caterpillar',
    name: 'Caterpillar',
    logo: 'https://logo.clearbit.com/caterpillar.com',
    ctc: '14.56 LPA (UG)',
    tier: 'Super Dream / Core',
    description: 'Caterpillar UG campus recruitment drive. CGPA Cutoff: 7.5. Eligible Depts: Mechanical, EEE, ECE and allied core branches.',
    tags: ['Core', 'Super Dream', 'CGPA: 7.5', 'Heavy Machinery'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'collins-aerospace',
    name: 'Collins Aerospace',
    logo: 'https://logo.clearbit.com/collinsaerospace.com',
    ctc: '8 LPA',
    tier: 'Dream / Core',
    description: 'Collins Aerospace campus recruitment for avionics and flight control systems. Eligible Depts: All Engineering branches.',
    tags: ['Core', 'Aerospace', 'Avionics'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'e-con-systems',
    name: 'E-Con Systems',
    logo: 'https://logo.clearbit.com/e-consystems.com',
    ctc: '8 LPA / 5 LPA',
    tier: 'Core Product',
    description: 'E-Con Systems embedded vision & camera solutions recruitment. CGPA Cutoff: 7.5. Eligible Depts: EEE, ECE, EIE & CSE.',
    tags: ['Core', 'Embedded', 'CGPA: 7.5', 'EEE', 'ECE', 'EIE', 'CSE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'ashok-leyland',
    name: 'Ashok Leyland',
    logo: 'https://logo.clearbit.com/ashokleyland.com',
    ctc: '7.5 LPA (after training); 5 LPA (GET)',
    tier: 'Core Automotive',
    description: 'Ashok Leyland Graduate Engineer Trainee (GET) recruitment. CGPA Cutoff: 7.0. Eligible Depts: Mechanical, Mechanical (Digital Manufacturing), Mechatronics, and All B.Tech branches from SEEE.',
    tags: ['Core', 'Automotive', 'CGPA: 7.0', 'Mech', 'SEEE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'syrma-sgs',
    name: 'Syrma SGS',
    logo: 'https://logo.clearbit.com/syrmasgs.com',
    ctc: '6 LPA (GET); 20k/month stipend',
    tier: 'Core Electronics',
    description: 'Syrma SGS GET & intern recruitment. CGPA Cutoff: 8.0. Eligible Depts: ECE / EEE / E&I / Mechatronics / Mechanical / Mechanical (DM) / IT / CSE.',
    tags: ['Core', 'Electronics', 'CGPA: 8.0', 'GET'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'american-megatrends',
    name: 'American Megatrends (AMI)',
    logo: 'https://logo.clearbit.com/ami.com',
    ctc: '6 LPA',
    tier: 'Core Firmware',
    description: 'American Megatrends (AMI) campus recruitment for UEFI, BIOS, and core systems. Eligible Depts: All branches.',
    tags: ['Core', 'Firmware', 'BIOS'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'coreel-technologies',
    name: 'CoreEL Technologies',
    logo: 'https://logo.clearbit.com/coreel.com',
    ctc: '5.22 LPA',
    tier: 'Core Defense',
    description: 'CoreEL Technologies recruitment for digital signal processing and FPGA design. CGPA Cutoff: 7.0. Eligible Depts: School of Electrical & Electronics Engineering (SEEE).',
    tags: ['Core', 'VLSI', 'Defense', 'CGPA: 7.0', 'SEEE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'aethrone-aerospace',
    name: 'Aethrone Aerospace',
    logo: 'https://logo.clearbit.com/aethrone.com',
    ctc: '3 LPA – 7 LPA',
    tier: 'Core Aerospace',
    description: 'Aethrone Aerospace recruitment drive for drone systems and flight dynamics. Eligible Depts: All Engineering branches.',
    tags: ['Core', 'Aerospace', 'Drones'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'brakes-india',
    name: 'Brakes India',
    logo: 'https://logo.clearbit.com/brakesindia.com',
    ctc: '3.79 LPA; 15k/month stipend',
    tier: 'Core Automotive',
    description: 'Brakes India recruitment for automotive design and manufacturing. CGPA Cutoff: 7.5. Eligible Depts: SEEE and Mechanical Engineering.',
    tags: ['Core', 'Automotive', 'CGPA: 7.5', 'SEEE', 'Mech'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'versa-drive',
    name: 'Versa Drive',
    logo: 'https://logo.clearbit.com/versadrive.in',
    ctc: 'Min 3 LPA (performance-based)',
    tier: 'Core Drives',
    description: 'Versa Drive recruitment for BLDC motor controllers & energy-efficient drive systems. Eligible Depts: All Engineering branches.',
    tags: ['Core', 'Power Electronics', 'BLDC Motors'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'delta-electronics',
    name: 'Delta Electronics',
    logo: 'https://logo.clearbit.com/deltaww.com',
    ctc: '6 LPA',
    tier: 'Core Automation',
    description: 'Delta Electronics industrial automation recruitment. CGPA Cutoff: 6.0. Eligible Depts: EEE, ECE, EIE, AI & Robotics, Mech, Mech (Dig.Mfg), Mechatronics.',
    tags: ['Core', 'Automation', 'Power', 'CGPA: 6.0'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'data-patterns',
    name: 'Data Patterns',
    logo: 'https://logo.clearbit.com/datapatternsindia.com',
    ctc: '4.2 LPA',
    tier: 'Core Defense',
    description: 'Data Patterns India campus recruitment. CGPA Cutoff: 6.5. Eligible Depts: School of Electrical & Electronics Engineering (SEEE).',
    tags: ['Core', 'Defense', 'CGPA: 6.5', 'SEEE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'tata-power',
    name: 'Tata Power',
    logo: 'https://logo.clearbit.com/tatapower.com',
    ctc: 'Not specified',
    tier: 'Core Energy',
    description: 'Tata Power campus drive for electrical power grid and renewable generation engineering. Eligible Depts: EEE.',
    tags: ['Core', 'Power', 'EEE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'tata-steel',
    name: 'Tata Steel',
    logo: 'https://logo.clearbit.com/tatasteel.com',
    ctc: 'Not specified',
    tier: 'Core Heavy Industry',
    description: 'Tata Steel campus recruitment for electrical and automation engineers. Eligible Depts: SEEE.',
    tags: ['Core', 'Steel', 'SEEE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'jsw-group',
    name: 'JSW Group',
    logo: 'https://logo.clearbit.com/jsw.in',
    ctc: '8 LPA',
    tier: 'Dream / Core',
    description: 'JSW Group campus recruitment. CGPA Cutoff: 7.0. Eligible Depts: EEE, EIE.',
    tags: ['Core', 'Infrastructure', 'CGPA: 7.0', 'EEE', 'EIE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'hyundai',
    name: 'Hyundai Motor India',
    logo: 'https://logo.clearbit.com/hyundai.com',
    ctc: '8 LPA',
    tier: 'Dream / Core',
    description: 'Hyundai Motor India campus recruitment for vehicle power systems. CGPA Cutoff: 7.0. Eligible Depts: EEE.',
    tags: ['Core', 'Automotive', 'CGPA: 7.0', 'EEE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'quest-global',
    name: 'Quest Global',
    logo: 'https://logo.clearbit.com/quest-global.com',
    ctc: '5.5 LPA (EIE) / 4.5 LPA (MECH)',
    tier: 'Core Engineering Services',
    description: 'Quest Global engineering R&D services recruitment. CGPA Cutoff: 6.0. Eligible Depts: EIE, EEE, Mechanical.',
    tags: ['Core', 'Engineering R&D', 'CGPA: 6.0', 'EIE', 'EEE', 'Mech'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'visteon',
    name: 'Visteon Corporation',
    logo: 'https://logo.clearbit.com/visteon.com',
    ctc: '7 LPA',
    tier: 'Core Electronics',
    description: 'Visteon automotive cockpit electronics & cluster software recruitment. CGPA Cutoff: 7.0. Eligible Depts: School of Electrical Engineering (SEE).',
    tags: ['Core', 'Automotive Electronics', 'CGPA: 7.0', 'SEE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'spectra-medicals',
    name: 'Spectra Medicals',
    logo: 'https://logo.clearbit.com/spectramedicals.com',
    ctc: '3.5 LPA',
    tier: 'Core MedTech',
    description: 'Spectra Medicals medical instrumentation recruitment. CGPA Cutoff: 6.0. Eligible Depts: SEEE.',
    tags: ['Core', 'MedTech', 'CGPA: 6.0', 'SEEE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'tata-technologies',
    name: 'Tata Technologies',
    logo: 'https://logo.clearbit.com/tatatechnologies.com',
    ctc: '4.5 LPA',
    tier: 'Core Product Engineering',
    description: 'Tata Technologies product engineering services drive. Eligible Depts: SEEE.',
    tags: ['Core', 'Product Engineering', 'SEEE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'ge-vernova',
    name: 'GE Vernova',
    logo: 'https://logo.clearbit.com/gevernova.com',
    ctc: '6 LPA',
    tier: 'Core Energy',
    description: 'GE Vernova electrification & grid solutions recruitment. CGPA Cutoff: 7.0. Eligible Depts: EEE.',
    tags: ['Core', 'Energy', 'CGPA: 7.0', 'EEE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'schneider',
    name: 'Schneider Electric',
    logo: 'https://logo.clearbit.com/se.com',
    ctc: '12 LPA',
    tier: 'Super Dream / Core',
    description: 'Schneider Electric GET & software engineer drive. CGPA Cutoff: 7.0. Eligible Depts: SEEE.',
    tags: ['Core', 'Super Dream', 'Automation', 'CGPA: 7.0', 'SEEE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'elgi',
    name: 'Elgi Equipments',
    logo: 'https://logo.clearbit.com/elgi.com',
    ctc: '8.5 LPA',
    tier: 'Core Manufacturing',
    description: 'Elgi Equipments GET campus recruitment. CGPA Cutoff: 7.0. Eligible Depts: Mechanical, EEE, ECE.',
    tags: ['Core', 'Machinery', 'CGPA: 7.0', 'Mech', 'EEE', 'ECE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'l-and-t',
    name: 'L&T (Larsen & Toubro)',
    logo: 'https://logo.clearbit.com/larsentoubro.com',
    ctc: '6 LPA',
    tier: 'Core Infrastructure',
    description: 'L&T Graduate Engineer Trainee (GET) campus recruitment. CGPA Cutoff: 6.0. Eligible Depts: SEEE.',
    tags: ['Core', 'Infrastructure', 'CGPA: 6.0', 'SEEE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'digital-connxion',
    name: 'Digital Connxion',
    logo: 'https://logo.clearbit.com/digitalconnxion.com',
    ctc: '10 LPA',
    tier: 'Core Infrastructure',
    description: 'Digital Connxion data center infrastructure engineering. CGPA Cutoff: 6.5. Eligible Depts: EEE.',
    tags: ['Core', 'Data Centers', 'CGPA: 6.5', 'EEE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'ace-micromatic',
    name: 'Ace Micromatic',
    logo: 'https://logo.clearbit.com/acemicromatic.com',
    ctc: '6.5 LPA',
    tier: 'Core Manufacturing',
    description: 'Ace Micromatic Group CNC machine tools recruitment. CGPA Cutoff: 8.0. Eligible Depts: All Core engineering.',
    tags: ['Core', 'CNC', 'CGPA: 8.0', 'Manufacturing'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'rane',
    name: 'Rane Group',
    logo: 'https://logo.clearbit.com/ranegroup.com',
    ctc: '4 LPA',
    tier: 'Core Automotive',
    description: 'Rane Group campus recruitment. CGPA Cutoff: 6.0. Eligible Depts: Mechanical, Mechanical Digital Manufacturing, Mechatronics and Electrical. Seats: 11 (3 reserved for EE).',
    tags: ['Core', 'Automotive', 'CGPA: 6.0', 'Mech', 'EE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'silicon-labs',
    name: 'Silicon Labs',
    logo: 'https://logo.clearbit.com/silabs.com',
    ctc: '50k / month (Internship)',
    tier: 'Core Semiconductor',
    description: 'Silicon Labs internship drive for wireless SOCs and IoT microcontrollers. CGPA Cutoff: 7.5. Eligible Depts: SEEE and SOC (School of Computing).',
    tags: ['Core', 'Internship', 'CGPA: 7.5', 'Semiconductor', 'SEEE', 'SOC'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'turbo-energy',
    name: 'Turbo Energy',
    logo: 'https://logo.clearbit.com/turboenergy.co.in',
    ctc: '3.69 LPA',
    tier: 'Core Automotive',
    description: 'Turbo Energy campus recruitment. CGPA Cutoff: 7.0. Eligible Depts: Mechanical, Mechanical (DM), Mechatronics, ECE, ECE(CPS), EEE & EEE(SGEV).',
    tags: ['Core', 'Automotive', 'CGPA: 7.0', 'Mech', 'ECE', 'EEE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'hcl-tech',
    name: 'HCL Tech',
    logo: 'https://logo.clearbit.com/hcltech.com',
    ctc: '4.5 LPA',
    tier: 'Core / IT Services',
    description: 'HCL Tech embedded systems and software drive. CGPA Cutoff: 7.0. Eligible Depts: SEEE.',
    tags: ['Core', 'IT Services', 'CGPA: 7.0', 'SEEE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'astrome',
    name: 'Astrome Technologies',
    logo: 'https://logo.clearbit.com/astrome.co',
    ctc: '10 LPA',
    tier: 'Core Telecom',
    description: 'Astrome Technologies mmWave satellite communication recruitment. CGPA Cutoff: 7.0. Eligible Depts: SEEE.',
    tags: ['Core', 'Telecom', 'SpaceTech', 'CGPA: 7.0', 'SEEE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'pioneer-wincon',
    name: 'Pioneer Wincon',
    logo: 'https://logo.clearbit.com/pioneerwincon.com',
    ctc: '4 to 5 LPA',
    tier: 'Core Renewable',
    description: 'Pioneer Wincon wind energy equipment drive. Eligible Depts: All branches.',
    tags: ['Core', 'Wind Energy', 'Renewable'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'proleed',
    name: 'Proleed',
    logo: 'https://logo.clearbit.com/proleed.in',
    ctc: '3 LPA',
    tier: 'Core Electrical',
    description: 'Proleed electrical controls drive. CGPA Cutoff: 6.5. Eligible Depts: EEE, ECE, SGEV.',
    tags: ['Core', 'Electrical', 'CGPA: 6.5', 'EEE', 'ECE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'hl-mando',
    name: 'HL Mando',
    logo: 'https://logo.clearbit.com/hlmando.com',
    ctc: '5 LPA',
    tier: 'Core Automotive',
    description: 'HL Mando vehicle safety systems drive. CGPA Cutoff: 7.0. Eligible Depts: Mechanical / Mechanical(DM) / Electrical / Electronics / Mechatronics.',
    tags: ['Core', 'Automotive', 'CGPA: 7.0', 'Mech', 'Electrical'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'amway',
    name: 'Amway India',
    logo: 'https://logo.clearbit.com/amway.in',
    ctc: '4.65 LPA',
    tier: 'Core Operations',
    description: 'Amway India plant operations drive. CGPA Cutoff: 8.0. Eligible Depts: Mech, Chem, EEE. Seats Available: 3.',
    tags: ['Core', 'Operations', 'CGPA: 8.0', 'Mech', 'Chem', 'EEE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'dalmia-cements',
    name: 'Dalmia Cements',
    logo: 'https://logo.clearbit.com/dalmiabharat.com',
    ctc: '5 LPA',
    tier: 'Core Heavy Industry',
    description: 'Dalmia Cements plant maintenance and electrical systems drive. CGPA Cutoff: 6.0. Eligible Depts: Mechanical, Mechanical DM, EEE, EIE, ECE, Chemical. Seats Available: 2.',
    tags: ['Core', 'Heavy Industry', 'CGPA: 6.0', 'Mech', 'EEE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'rosenberg',
    name: 'Rosenberg',
    logo: 'https://logo.clearbit.com/rosenberg-gmbh.com',
    ctc: '4 LPA',
    tier: 'Core HVAC',
    description: 'Rosenberg industrial fan systems recruitment. CGPA Cutoff: 6.0. Eligible Depts: SEEE and Mech.',
    tags: ['Core', 'HVAC', 'CGPA: 6.0', 'SEEE', 'Mech'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'bosch-global-software',
    name: 'Bosch Global Software (BGST)',
    logo: 'https://logo.clearbit.com/bosch.com',
    ctc: '30K pm (Internship)',
    tier: 'Core Mobility Software',
    description: 'Bosch Global Software Technologies (BGST) internship & full-time drive. CGPA Cutoff: 7.0. Eligible Depts: Circuit Branches and Mech.',
    tags: ['Core', 'Automotive Software', 'CGPA: 7.0', 'Circuit', 'Mech'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'kcp-ltd',
    name: 'KCP Ltd',
    logo: 'https://logo.clearbit.com/kcp.co.in',
    ctc: '18k pm (Stipend)',
    tier: 'Core Heavy Engineering',
    description: 'KCP Ltd industrial machinery drive. CGPA Cutoff: 6.0. Eligible Depts: EIE Males.',
    tags: ['Core', 'Heavy Engineering', 'CGPA: 6.0', 'EIE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'sv-tech',
    name: 'SV Tech',
    logo: 'https://logo.clearbit.com/svtechnologies.com',
    ctc: '5 LPA',
    tier: 'Core RTL Design',
    description: 'SV Tech RTL design and digital verification drive. CGPA Cutoff: 8.0. Eligible Depts: SEEE (RTL oriented).',
    tags: ['Core', 'VLSI', 'RTL', 'CGPA: 8.0', 'SEEE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'ip-rings',
    name: 'IP Rings',
    logo: 'https://logo.clearbit.com/iprings.com',
    ctc: '3.5 - 4.5 LPA',
    tier: 'Core Automotive',
    description: 'IP Rings engine component manufacturing recruitment. CGPA Cutoff: 6.0. Eligible Depts: Mechanical, Mechanical DM, Mechatronics and All branches from School of EEE.',
    tags: ['Core', 'Automotive', 'CGPA: 6.0', 'Mech', 'SEEE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'ascent-circuits',
    name: 'Ascent Circuits',
    logo: 'https://logo.clearbit.com/ascentcircuits.com',
    ctc: '5 LPA',
    tier: 'Core PCB Tech',
    description: 'Ascent Circuits PCB fabrication recruitment. CGPA Cutoff: 7.0. Eligible Depts: Mechanical (only males), ECE, EEE, Chemical Engineering.',
    tags: ['Core', 'PCB Tech', 'CGPA: 7.0', 'ECE', 'EEE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'jean-mueller',
    name: 'Jean Mueller',
    logo: 'https://logo.clearbit.com/jeanmueller.de',
    ctc: '5.8 LPA',
    tier: 'Core Switchgear',
    description: 'Jean Mueller electrical distribution and protection systems. CGPA Cutoff: 8.0. Eligible Depts: EEE & SGEV.',
    tags: ['Core', 'Electrical Protection', 'CGPA: 8.0', 'EEE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  },
  {
    id: 'bpl-medical-tech',
    name: 'BPL Medical Tech',
    logo: 'https://logo.clearbit.com/bplmedicaltechnologies.com',
    ctc: '4 LPA',
    tier: 'Core MedTech',
    description: 'BPL Medical Technologies healthcare equipment drive. CGPA Cutoff: 6.5. Eligible Depts: EEE, ECE.',
    tags: ['Core', 'MedTech', 'CGPA: 6.5', 'EEE', 'ECE'],
    isSaved: false,
    rounds: [],
    pyqs: [],
    resources: []
  }
];

// Append before export const mockCompanies = ... or merge into array
const insertMarker = 'export const mockCompanies = [';
const idx = mockDataContent.indexOf(insertMarker);

if (idx !== -1) {
  const insertPos = idx + insertMarker.length;
  const formattedStr = '\n' + newCompanies.map(c => `  ${JSON.stringify(c, null, 4).replace(/\n/g, '\n  ')},`).join('\n') + '\n';
  const updatedContent = mockDataContent.slice(0, insertPos) + formattedStr + mockDataContent.slice(insertPos);
  fs.writeFileSync(mockDataPath, updatedContent, 'utf8');
  console.log('✅ Successfully updated src/constants/mockData.js with 45 core companies!');
} else {
  console.error('❌ Could not find mockCompanies array in mockData.js');
}
